<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoursePlatform.API\CoursePlatform.API.csproj" />
    <ProjectReference Include="..\CoursePlatform.Application\CoursePlatform.Application.csproj" />
    <ProjectReference Include="..\CoursePlatform.Domain\CoursePlatform.Domain.csproj" />
    <ProjectReference Include="..\CoursePlatform.Infrastructure\CoursePlatform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
